' <auto-generated />
Imports System
Imports Intro
Imports Microsoft.EntityFrameworkCore
Imports Microsoft.EntityFrameworkCore.Infrastructure
Imports Microsoft.EntityFrameworkCore.Metadata
Imports Microsoft.EntityFrameworkCore.Migrations

Namespace Global.Intro.Migrations
    <DbContext(GetType(BloggingContext))>
    Partial Class BloggingContextModelSnapshot
        Inherits ModelSnapshot

        Protected Overrides Sub BuildModel(modelBuilder As ModelBuilder)
            modelBuilder.
                HasAnnotation("Relational:MaxIdentifierLength", 128).
                HasAnnotation("ProductVersion", "5.0.6").
                HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn)

            modelBuilder.Entity("Intro.Blog",
                Sub(b)
                    b.Property(Of Integer)("BlogId").
                        ValueGeneratedOnAdd().
                        HasColumnType("int").
                        HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn)

                    b.Property(Of Integer)("Rating").
                        HasColumnType("int")

                    b.Property(Of String)("Url").
                        HasColumnType("nvarchar(max)")

                    b.HasKey("BlogId")

                    b.ToTable("Blogs")
                End Sub)

            modelBuilder.Entity("Intro.Post",
                Sub(b)
                    b.Property(Of Integer)("PostId").
                        ValueGeneratedOnAdd().
                        HasColumnType("int").
                        HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn)

                    b.Property(Of Integer)("BlogId").
                        HasColumnType("int")

                    b.Property(Of String)("Content").
                        HasColumnType("nvarchar(max)")

                    b.Property(Of String)("Title").
                        HasColumnType("nvarchar(max)")

                    b.HasKey("PostId")

                    b.HasIndex("BlogId")

                    b.ToTable("Posts")
                End Sub)

            modelBuilder.Entity("Intro.Post",
                Sub(b)
                    b.HasOne("Intro.Blog", "Blog").
                        WithMany("Posts").
                        HasForeignKey("BlogId").
                        OnDelete(DeleteBehavior.Cascade).
                        IsRequired()
                    b.Navigation("Blog")
                End Sub)

            modelBuilder.Entity("Intro.Blog",
                Sub(b)
                    b.Navigation("Posts")
                End Sub)
        End Sub
    End Class
End Namespace
