' <auto-generated />
Imports System
Imports DataSeeding
Imports Microsoft.EntityFrameworkCore
Imports Microsoft.EntityFrameworkCore.Infrastructure
Imports Microsoft.EntityFrameworkCore.Metadata
Imports Microsoft.EntityFrameworkCore.Migrations

Namespace Global.DataSeeding.Migrations
    <DbContext(GetType(DataSeedingContext))>
    <Migration("20210521164706_Initial")>
    Partial Class Initial
        Protected Overrides Sub BuildTargetModel(modelBuilder As ModelBuilder)
            modelBuilder.
                HasAnnotation("Relational:MaxIdentifierLength", 128).
                HasAnnotation("ProductVersion", "5.0.6").
                HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn)

            modelBuilder.Entity("DataSeeding.Blog",
                Sub(b)
                    b.Property(Of Integer)("BlogId").
                        ValueGeneratedOnAdd().
                        HasColumnType("int").
                        HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn)

                    b.Property(Of String)("Url").
                        IsRequired().
                        HasColumnType("nvarchar(max)")

                    b.HasKey("BlogId")

                    b.ToTable("Blogs")

                    b.HasData({
                        New With {
                            .BlogId = 1,
                            .Url = "http://sample.com"
                         }
                    })
                End Sub)

            modelBuilder.Entity("DataSeeding.Post",
                Sub(b)
                    b.Property(Of Integer)("PostId").
                        ValueGeneratedOnAdd().
                        HasColumnType("int").
                        HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn)

                    b.Property(Of Integer)("BlogId").
                        HasColumnType("int")

                    b.Property(Of String)("Content").
                        HasColumnType("nvarchar(max)")

                    b.Property(Of String)("Title").
                        HasColumnType("nvarchar(max)")

                    b.HasKey("PostId")

                    b.HasIndex("BlogId")

                    b.ToTable("Posts")

                    b.HasData({
                        New With {
                            .PostId = 1,
                            .BlogId = 1,
                            .Content = "Test 1",
                            .Title = "First post"
                         },
                        New With {
                            .PostId = 2,
                            .BlogId = 1,
                            .Content = "Test 2",
                            .Title = "Second post"
                         }
                    })
                End Sub)

            modelBuilder.Entity("DataSeeding.Post",
                Sub(b)
                    b.HasOne("DataSeeding.Blog", "Blog").
                        WithMany("Posts").
                        HasForeignKey("BlogId").
                        OnDelete(DeleteBehavior.Cascade).
                        IsRequired()

                    b.OwnsOne("DataSeeding.Name", "AuthorName",
                        Sub(b1)
                            b1.Property(Of Integer)("PostId").
                                ValueGeneratedOnAdd().
                                HasColumnType("int").
                                HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn)

                            b1.Property(Of String)("First").
                                HasColumnType("nvarchar(max)")

                            b1.Property(Of String)("Last").
                                HasColumnType("nvarchar(max)")

                            b1.HasKey("PostId")

                            b1.ToTable("Posts")
                            b1.WithOwner().
                                HasForeignKey("PostId")

                            b1.HasData({
                                New With {
                                    .PostId = 1,
                                    .First = "Andriy",
                                    .Last = "Svyryd"
                                 },
                                New With {
                                    .PostId = 2,
                                    .First = "Diego",
                                    .Last = "Vega"
                                 }
                            })
                        End Sub)
                    b.Navigation("AuthorName")

                    b.Navigation("Blog")
                End Sub)

            modelBuilder.Entity("DataSeeding.Blog",
                Sub(b)
                    b.Navigation("Posts")
                End Sub)

        End Sub
    End Class
End Namespace
